# Site settings
title: On Particles and Processors
email: lmarkley12@gmail.community
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lmarkley.github.io" # the base hostname & protocol for your site
enable_retina: true
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  About : ['About', '/about', 'fa-anchor']
  Contact : ['Contact', '/contact', 'fa-plane']
footer_links:
    About: ['About', '/about']


# Build settings
markdown: kramdown
